#!/usr/bin/env python3
import sys


def replace_tab(sentence, tabstop=4):
    """
    It replaces all tabs in a string with the adequate number of spaces.

    Args:
        sentence (str): The string to replace tabs in.
        tabstop (int, optional): The tab size. Defaults to 4.

    Returns:
        str: The string with tabs replaced by spaces.
    """
    result = ""
    for character in sentence:
        if character == '\t':
            result += ' '
            while len(result) % tabstop != 0:
                result += ' '
        else:
            result += character
    return result


def capture_input_args():
    """
    It captures the input arguments for the program.

    Returns:
        str, int: The name of the file to process and the tab size.
    """

    usage = "\nUsage: detab <filename> [tabsize]\n"

    try:
        filename = sys.argv[1]

    except IndexError:
        print(usage)
        sys.exit(1)

    try:
        n_tabs = int(sys.argv[2])

    except ValueError:
        print(f"\nInvalid tab size: {sys.argv[2]}\n")
        print(usage)
        sys.exit(1)

    except IndexError:
        print("\nNo tab size specified, using default of 4 spaces.")
        n_tabs = 4

    return filename, n_tabs


def main():

    filename, n_tabs = capture_input_args()

    # We open the file in read mode,
    # and read the whole file into a list.
    try:
        with open(filename, 'r') as file:
            lines = file.readlines()

    except FileNotFoundError:
        print(f"\nFile '{filename}' not found.\n")
        sys.exit(1)

    except PermissionError:
        print(f"\nInsufficient permissions to open '{filename}'.\n")
        sys.exit(2)

    # We replace all tabs in the list with spaces
    # and write the result to the file.
    try:
        with open(filename, 'w') as file:

            untabbed_lines = [replace_tab(line, n_tabs)
                              for line
                              in lines]

            file.writelines(untabbed_lines)

    except Exception:
        print(f"\nUnable to open '{filename}' for writing.\n")
        sys.exit(1)

    print(f"\nReplaced all tabs in '{filename}'.\n")


if __name__ == '__main__':
    main()
